""""['Add admin field to User']"

Revision ID: 75cb8d38a293
Revises: 4bd7684fb6ae
Create Date: 2020-04-07 17:00:08.890482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cb8d38a293'
down_revision = '4bd7684fb6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
